name: "BitcoinVN BTM"
since: 2014
url: "https://bitcoinvn.io/btm"
exchangeUrl: "https://bitcoinvn.io"
mapsUrl: "https://maps.app.goo.gl/PgTbKpKzfcebuAxi6"

contact:
  email: "support+btm@bitcoinvn.io"
  telegram:
    url: "https://t.me/BitcoinATMHCMC"
    handle: "@BitcoinATMHCMC"
  facebook:
    url: "https://www.facebook.com/BitcoinATMHCMC"
    handle: "@BitcoinATMHCMC"

notice:
  enabled: true

supported_assets:
  - ticker: "BTC"
    buy: true
    sell: true
  - ticker: "USDT"
    buy: true
    sell: true
  - ticker: "USDC"
    buy: true
    sell: true
